/* modules/interview.js — Learning · searchable interview bank, 3 levels */
(function () {
  "use strict";
  var NS = (window.DECICDViz = window.DECICDViz || {});

  var DATA = {
    beginner: [
      { q: "What is version control and why does RetailFlow need it?", a: "Version control records the full history of every change to code and lets many engineers work in parallel without overwriting each other.", why: "Without it, teams keep files like <code>pipeline_final_v2.py</code> and lose track of what's live.", mistake: "Thinking version control is just backups — it's also collaboration, history, and safe rollback.", retailflow: "RetailFlow tracks every edit to the <code>net_revenue</code> formula so it can see exactly who changed it and when.", followup: "How does Git differ from a centralized VCS like SVN?" },
      { q: "What is a commit?", a: "A commit is a saved snapshot of staged changes with a message describing what changed.", why: "Commits are the atomic units of history you can review, revert, and cherry-pick.", mistake: "Writing vague messages like 'fix' that tell future-you nothing.", retailflow: "The revenue fix is one commit: <code>Fix net revenue: subtract refunds, not add</code>.", followup: "What's the difference between the working directory, staging area, and a commit?" },
      { q: "What is a branch?", a: "A branch is an independent line of development that lets you work on a change without affecting <code>main</code>.", why: "It isolates risky work so production code stays stable.", mistake: "Committing directly to <code>main</code> instead of branching.", retailflow: "<code>feature/fix-net-revenue</code> holds the change while the nightly pipeline runs untouched.", followup: "What is a long-lived vs short-lived branch, and which suits data teams?" },
      { q: "What is a pull request?", a: "A pull request proposes merging one branch into another, bundling the diff, review comments, and CI results.", why: "It's the gate where humans and automation inspect a change before it lands.", mistake: "Treating a PR as a rubber stamp and skipping real review.", retailflow: "The revenue fix reaches <code>main</code> only after a reviewer approves the PR and CI passes.", followup: "What is a branch protection rule?" },
      { q: "What does merge mean in Git?", a: "Merge combines the changes from one branch into another, creating a merge commit when the histories diverged.", why: "It's how completed work rejoins the main line.", mistake: "Assuming merges never conflict — they do when both sides edit the same lines.", retailflow: "After approval, the revenue-fix branch is merged into <code>main</code>.", followup: "What is a merge conflict and how do you resolve one?" },
      { q: "What is CI (Continuous Integration)?", a: "CI automatically builds and tests every change as it's pushed so problems are caught immediately.", why: "It shrinks feedback from days to minutes and keeps <code>main</code> always working.", mistake: "Confusing CI (build/test) with CD (deploy).", retailflow: "RetailFlow's CI runs dbt and pytest on every PR touching the revenue transform.", followup: "How is CI different from CD?" },
      { q: "What is CD?", a: "CD is Continuous Delivery (auto-promote a validated build, deploy on approval) or Continuous Deployment (auto-deploy every green build to prod).", why: "It makes releases routine and low-risk instead of rare and scary.", mistake: "Using the terms interchangeably without noting delivery keeps a manual gate.", retailflow: "RetailFlow auto-deploys to staging but requires approval before prod.", followup: "When would you choose delivery over deployment?" },
      { q: "What is a CI/CD pipeline?", a: "A pipeline is an automated sequence of stages — build, test, package, deploy — that every change travels through.", why: "It standardizes how software ships so every change is treated the same.", mistake: "Confusing a data pipeline with a CI/CD pipeline; they're different things that RetailFlow has both of.", retailflow: "The revenue fix flows through lint → test → build image → deploy to staging → deploy to prod.", followup: "What triggers a pipeline to run?" },
      { q: "What is a Docker image?", a: "An image is an immutable, layered blueprint that bundles code with its exact dependencies.", why: "It guarantees the same software runs everywhere, ending 'works on my machine'.", mistake: "Confusing an image (blueprint) with a container (running instance).", retailflow: "RetailFlow bakes Python, dbt, and the transforms into one image.", followup: "What's the difference between an image and a container?" },
      { q: "What is a container?", a: "A container is a running, isolated instance of an image.", why: "Containers make deployments reproducible and disposable.", mistake: "Thinking a container is a lightweight VM — it shares the host kernel, no full OS.", retailflow: "The revenue job runs in a container identical on a laptop and in prod.", followup: "How does a container differ from a virtual machine?" },
      { q: "What is a repository?", a: "A repository is the project's home — all its source, config, and full change history in one place.", why: "It's the single source of truth the whole team works from.", mistake: "Committing large data files or secrets into the repo.", retailflow: "The <code>daily-revenue-pipeline</code> repo holds transforms, tests, and workflows together.", followup: "What kinds of files should never be committed to a repo?" },
      { q: "What is a .gitignore file?", a: "It lists files and patterns Git should not track, like build outputs, secrets, and local config.", why: "It keeps noise and sensitive data out of history.", mistake: "Forgetting to ignore <code>.env</code> and leaking credentials.", retailflow: "RetailFlow ignores <code>target/</code> from dbt and any <code>.env</code> with warehouse creds.", followup: "How do you remove a file already committed that should have been ignored?" },
      { q: "What is a runner (or agent)?", a: "A runner is the machine or container that executes CI/CD jobs.", why: "It's where your build and tests actually run.", mistake: "Assuming runner state persists between jobs — most are ephemeral.", retailflow: "A GitHub Actions runner installs dbt, runs RetailFlow's tests, then vanishes.", followup: "What's the difference between hosted and self-hosted runners?" },
      { q: "What is an artifact in CI/CD?", a: "An artifact is a versioned build output — an image, a wheel, a compiled dbt manifest — that gets promoted between stages.", why: "Building once and promoting the same artifact ensures prod runs exactly what was tested.", mistake: "Rebuilding per environment, so staging and prod aren't identical.", retailflow: "RetailFlow builds <code>revenue-pipeline:sha-abc123</code> once and deploys it to every stage.", followup: "Why is 'build once, deploy everywhere' important?" },
      { q: "What is a secret in CI/CD?", a: "A secret is a sensitive value like a password or token, stored outside source and injected at runtime.", why: "Hardcoding secrets in code leaks them to anyone with repo access.", mistake: "Printing secrets to CI logs or committing them.", retailflow: "RetailFlow's warehouse password lives in a secret store, never in Git.", followup: "Where should secrets be stored instead of in code?" },
      { q: "What is a dbt model?", a: "A dbt model is a single SQL SELECT file that dbt materializes as a managed, tested table or view.", why: "It turns ad-hoc SQL into version-controlled, testable transformations.", mistake: "Running SQL by hand instead of as a tracked model.", retailflow: "The <code>daily_revenue</code> model computes <code>gross_revenue - refund_amount</code>.", followup: "What is a dbt test and how does it protect data?" },
      { q: "What is an environment (dev/staging/prod)?", a: "An environment is a named, isolated stage with its own data, secrets, and approvals.", why: "It lets you validate changes safely before they reach real users.", mistake: "Testing directly in prod because 'it's just a small change'.", retailflow: "The revenue fix is proven in staging before touching the 7 AM dashboard.", followup: "What should differ between staging and prod, and what should stay the same?" },
      { q: "What is a rollback?", a: "A rollback returns a system to a known-good previous version after a bad deploy.", why: "Fast rollback limits the blast radius of a bad change.", mistake: "Assuming code rollback also fixes bad data it already wrote.", retailflow: "RetailFlow redeploys the previous image to undo a broken revenue release.", followup: "How does rolling back code differ from rolling back data?" },
      { q: "What is Terraform, in one sentence?", a: "Terraform is an infrastructure-as-code tool that declares cloud resources in files and reconciles reality to match.", why: "It makes infrastructure reproducible, reviewable, and version-controlled.", mistake: "Clicking in the cloud console, causing drift from the code.", retailflow: "RetailFlow provisions its warehouse and job clusters with Terraform.", followup: "What is Terraform state and why does it matter?" },
      { q: "What is data quality?", a: "Data quality is the measured fitness of data — accuracy, completeness, uniqueness, freshness, and validity.", why: "A pipeline can be technically green while producing wrong numbers.", mistake: "Testing only that the job ran, not that the data is correct.", retailflow: "RetailFlow checks that <code>net_revenue</code> is never negative before publishing.", followup: "Name a data-quality check you'd add after deploying a revenue change." },
      { q: "What is a DAG?", a: "A DAG is a directed acyclic graph of tasks — dependencies with no cycles — defining order and parallelism.", why: "It makes complex pipeline dependencies explicit and schedulable.", mistake: "Assuming a DAG implies a schedule; the schedule is separate.", retailflow: "RetailFlow's nightly revenue run is an Airflow DAG of extract → transform → test → publish.", followup: "Where else besides Airflow do you meet DAGs in data engineering?" }
    ],
    intermediate: [
      { q: "Merge vs rebase — when do you use each?", a: "Merge preserves history and creates a merge commit; rebase rewrites your commits onto the latest base for a linear history. Merge for shared/public branches, rebase for tidying your own local feature branch before a PR.", why: "The wrong choice either clutters history or rewrites shared commits others depend on.", mistake: "Rebasing a branch others have already pulled, breaking their history.", retailflow: "The engineer rebases <code>feature/fix-net-revenue</code> onto <code>main</code> locally, then merges via PR.", followup: "What does 'never rebase a public branch' mean and why?" },
      { q: "What is a merge conflict and how do you resolve it?", a: "A conflict happens when two branches change the same lines; Git marks both versions and you manually choose or combine, then commit the resolution.", why: "Conflicts are normal in parallel work; resolving them wrongly can reintroduce bugs.", mistake: "Blindly accepting one side without understanding the other's intent.", retailflow: "Two engineers edited the revenue CTE; the conflict forces a deliberate merge of both changes.", followup: "How can you reduce the frequency of conflicts on a busy repo?" },
      { q: "What's the difference between a Docker image and a container?", a: "An image is the immutable blueprint; a container is a running, writable instance of it. One image spawns many containers.", why: "Confusing them leads to wrong mental models of state and persistence.", mistake: "Storing important data inside a container's writable layer, which is lost on restart.", retailflow: "RetailFlow's one revenue image runs as separate containers in dev, staging, and prod.", followup: "How do you persist data a container produces?" },
      { q: "What is Terraform state and why is it critical?", a: "State is Terraform's record of which real resources it manages and their attributes; it maps config to reality and enables diffing.", why: "Without accurate state Terraform can't tell what to create, change, or destroy.", mistake: "Keeping state locally so teammates clobber each other; it belongs in remote, locked storage.", retailflow: "RetailFlow stores warehouse state in a locked remote backend so CI and engineers stay consistent.", followup: "What is state locking and why does it matter for teams?" },
      { q: "What is configuration drift and how do you catch it?", a: "Drift is when real infrastructure diverges from the code (a manual console change). You catch it with <code>terraform plan</code> or a scheduled drift-detection job.", why: "Undetected drift causes deploys to behave unexpectedly.", mistake: "Fixing drift by editing the console again instead of the code.", retailflow: "Someone bumped the RetailFlow cluster size manually; the next plan flags the diff.", followup: "How would you prevent manual console changes entirely?" },
      { q: "How does Slim CI make dbt faster?", a: "Slim CI uses the production manifest to run only the models and tests affected by a change (<code>state:modified+</code>) instead of the whole project.", why: "Rebuilding everything on each PR wastes minutes and warehouse cost.", mistake: "Forgetting to store the prod manifest as an artifact, so state comparison can't work.", retailflow: "A change to <code>daily_revenue</code> rebuilds only it and its downstream models in CI.", followup: "What artifact does Slim CI compare against, and where is it stored?" },
      { q: "How do you deploy dbt changes through CI/CD?", a: "On PR, run <code>dbt build</code> (or Slim CI) against a CI schema; on merge, deploy to staging then prod, running tests as a gate before promotion.", why: "It ensures transformations and their tests both pass before data changes.", mistake: "Deploying models but skipping tests, letting bad data through.", retailflow: "RetailFlow blocks the revenue PR if the uniqueness test on <code>order_id</code> fails.", followup: "Should a failing dbt test block Terraform from deploying infra?" },
      { q: "How are Databricks Asset Bundles deployed across environments?", a: "A bundle defines jobs, notebooks, and config in YAML; <code>databricks bundle deploy -t <target></code> ships the same bundle to dev/staging/prod, swapping workspace, cluster, and schedule per target.", why: "It makes Databricks jobs version-controlled and promoted consistently.", mistake: "Hand-editing jobs in the workspace UI, so deployments drift from the bundle.", retailflow: "RetailFlow deploys the revenue job to the <code>staging</code> target, then <code>prod</code>.", followup: "What does a target let you override between environments?" },
      { q: "How do you deploy Airflow DAGs via CI/CD?", a: "CI lints and unit-tests DAGs, then CD syncs the DAG files to the scheduler's dags folder (git-sync, object storage, or baked into an image).", why: "Manual DAG copies drift and break silently.", mistake: "Putting heavy logic at DAG parse time, slowing the scheduler and failing imports.", retailflow: "RetailFlow's revenue DAG is validated in CI, then git-synced to the Airflow cluster.", followup: "How do you test that a DAG has no import errors before deploy?" },
      { q: "What is OIDC and why prefer it over stored cloud keys?", a: "OIDC lets a CI job prove its identity to the cloud and receive short-lived credentials, eliminating long-lived stored secrets.", why: "Static keys leak and rarely rotate; OIDC tokens are ephemeral and scoped.", mistake: "Keeping a long-lived service-principal secret in CI when OIDC is available.", retailflow: "RetailFlow's GitHub Actions assume a cloud role via OIDC to deploy, storing no key.", followup: "What trust configuration must exist on the cloud side for OIDC to work?" },
      { q: "How do you promote a build across environments correctly?", a: "Build one immutable artifact, then promote that same artifact through dev → staging → prod, swapping only config and secrets per stage.", why: "Rebuilding per stage means prod runs untested bits.", mistake: "Rebuilding the image in each environment's pipeline.", retailflow: "RetailFlow promotes <code>revenue-pipeline:sha-abc123</code> unchanged from staging to prod.", followup: "How do you inject environment-specific config without rebuilding?" },
      { q: "How do you promote a data artifact vs a code artifact?", a: "Code artifacts (images, wheels) are immutable and promoted by reference; data artifacts (tables, models) are promoted by running the validated transformation against each environment's data, gated by tests.", why: "Data can't be copied blindly between environments due to volume, privacy, and freshness.", mistake: "Copying prod data to staging without masking, leaking PII.", retailflow: "The revenue model's SQL is promoted; each environment rebuilds its own tables from its own data.", followup: "Why can't you just copy the prod revenue table to staging?" },
      { q: "How do you handle a schema change safely in a pipeline?", a: "Use expand-and-contract: add the new column, backfill, switch readers, then remove the old — with dbt contracts and CI checks catching breaks.", why: "A hard rename breaks every downstream consumer at once.", mistake: "Renaming <code>refund_amount</code> in one PR and breaking the revenue model instantly.", retailflow: "RetailFlow adds <code>refund_amount_v2</code>, migrates readers, then drops the old column.", followup: "What is a dbt model contract and how does it guard schema?" },
      { q: "Rollback: code vs data — how do they differ?", a: "Rolling back code redeploys the previous artifact instantly; rolling back data means restoring, reprocessing, or reverting the rows the bad code already wrote.", why: "Reverting code doesn't un-write incorrect numbers already in tables.", mistake: "Reverting the PR and assuming the wrong revenue rows fix themselves.", retailflow: "RetailFlow redeploys the old image and reprocesses the affected day's partition to correct revenue.", followup: "What table design (partitioning, snapshots) makes data rollback easier?" },
      { q: "How do you verify data quality after a deploy?", a: "Run post-deploy data tests and freshness/volume/row-count anomaly checks, and compare key metrics against expected ranges before declaring success.", why: "A green deploy can still produce wrong data.", mistake: "Alerting only on job failure, not on silently wrong values.", retailflow: "After deploy, RetailFlow asserts <code>net_revenue</code> is within a sane band vs yesterday.", followup: "What's the difference between a schema test and a business-rule test?" },
      { q: "GitHub Actions vs Azure DevOps vs Jenkins — how do they compare?", a: "Actions is GitHub-native YAML with a huge marketplace; Azure DevOps is an integrated Microsoft suite (Repos/Pipelines/Boards); Jenkins is self-hosted, plugin-driven, maximally flexible but higher maintenance.", why: "The right tool depends on your ecosystem, control needs, and ops capacity.", mistake: "Picking Jenkins for its flexibility then drowning in plugin upkeep.", retailflow: "RetailFlow on GitHub uses Actions; a sister team on Azure uses Pipelines for the same flow.", followup: "When would self-hosted Jenkins still be the right call?" },
      { q: "Docker vs Kubernetes — what's the relationship?", a: "Docker builds and runs individual containers; Kubernetes orchestrates many containers across a cluster — scheduling, scaling, healing, networking.", why: "They solve different layers; Kubernetes runs containers, it doesn't replace building them.", mistake: "Thinking you must have Kubernetes to use containers.", retailflow: "RetailFlow builds images with Docker and runs Airflow workers on Kubernetes.", followup: "When is Kubernetes overkill for a data team?" },
      { q: "What is Argo CD and how does GitOps deploy differ from push-based CI/CD?", a: "Argo CD watches a Git repo and pulls the cluster into the declared state; GitOps is pull/reconcile-based, whereas classic CI/CD pushes deploys from the pipeline.", why: "Pull-based deploys give continuous drift correction and a clear audit trail.", mistake: "Letting the CI pipeline also push to the cluster, bypassing the GitOps source of truth.", retailflow: "RetailFlow's Airflow manifests live in Git; Argo CD syncs the cluster to match <code>main</code>.", followup: "How do you roll back with GitOps?" },
      { q: "How do you unit-test PySpark transformations?", a: "Instantiate a local SparkSession in pytest, build small input DataFrames, run the transform function, and assert on the output DataFrame's rows.", why: "Testing logic on tiny local data catches bugs without a cluster.", mistake: "Testing against the whole warehouse, making tests slow and flaky.", retailflow: "RetailFlow unit-tests the net-revenue function on a five-row DataFrame in CI.", followup: "How do you keep Spark unit tests fast in CI?" },
      { q: "What is a Helm chart and a release?", a: "A chart is a versioned, parameterized package of Kubernetes templates; a release is a specific installed instance of that chart with resolved values and a revision history.", why: "Charts make complex deployments repeatable and rollback-able.", mistake: "Editing live manifests instead of the chart values, causing drift.", retailflow: "RetailFlow installs Airflow as one Helm release, rolling back a bad upgrade with <code>helm rollback</code>.", followup: "How does <code>helm rollback</code> know the previous state?" },
      { q: "What is a quality gate and what should it check for a data pipeline?", a: "A quality gate is a pass/fail checkpoint before promotion, checking test pass rate, coverage, security scan, and data tests.", why: "It prevents known-bad changes from advancing.", mistake: "Setting the gate to warn-only so it never actually blocks.", retailflow: "RetailFlow's gate blocks any revenue PR where dbt tests or coverage regress.", followup: "Should a data-quality failure block infra deployment? Why?" },
      { q: "How does a container registry fit into CI/CD?", a: "CI builds and pushes a tagged image to the registry; each environment pulls the exact same immutable image by tag or digest.", why: "It's the handoff point that guarantees identical software everywhere.", mistake: "Using the <code>latest</code> tag so environments pull different images over time.", retailflow: "RetailFlow tags images by commit SHA and pulls by digest in prod.", followup: "Why prefer pinning by digest over the <code>latest</code> tag?" },
      { q: "What does SonarQube add to a pipeline?", a: "SonarQube runs static analysis for bugs, code smells, coverage, and vulnerabilities, and enforces a quality gate that can fail the build.", why: "It catches maintainability and security issues automated tests miss.", mistake: "Ignoring the gate by marking every issue 'won't fix'.", retailflow: "RetailFlow's PR fails Sonar's gate when new transform code drops below coverage threshold.", followup: "How do you handle a Sonar gate on legacy code with low coverage?" },
      { q: "What is blue/green deployment?", a: "You run two identical environments (blue live, green idle), deploy to the idle one, verify, then switch traffic; rollback is an instant switch back.", why: "It gives near-zero-downtime releases and instant rollback.", mistake: "Forgetting that the database is often shared, so schema changes still need care.", retailflow: "RetailFlow could stand up a green revenue stack, validate, then flip the dashboard's source.", followup: "How do blue/green and canary differ?" },
      { q: "What is a canary release and when is it useful?", a: "A canary sends a small slice of traffic or data to the new version, watches metrics, then widens gradually.", why: "It limits the blast radius of a subtle regression.", mistake: "Canarying without metrics to compare, so you can't tell if it's healthy.", retailflow: "RetailFlow routes 5% of revenue processing to the new logic and compares outputs before full rollout.", followup: "What signals decide whether to promote or abort a canary?" },
      { q: "What is RBAC and how does it apply to CI/CD?", a: "RBAC grants permissions to roles rather than individuals; the CI service identity gets only the permissions it needs (least privilege).", why: "Over-privileged pipelines are a top breach vector.", mistake: "Giving CI admin/owner rights 'to make it work'.", retailflow: "RetailFlow's deploy identity can update the revenue job but can't read customer PII.", followup: "What is least privilege and how do you enforce it in a pipeline?" },
      { q: "How do you keep secrets out of CI logs and images?", a: "Inject secrets at runtime from a vault, mark them as masked in the CI tool, never bake them into image layers, and scan for accidental leaks.", why: "Secrets in logs or image history are exposed to anyone with access.", mistake: "Passing a secret as a build ARG, which persists in image layers.", retailflow: "RetailFlow mounts warehouse creds at runtime, never in the revenue image.", followup: "Why is a build ARG a bad place for a secret?" },
      { q: "What is idempotency and why does it matter for pipelines?", a: "An idempotent operation gives the same result whether run once or many times, so reruns and retries are safe.", why: "Pipelines fail and retry; non-idempotent steps double-count or corrupt data.", mistake: "Appending rows on each run instead of overwriting the partition.", retailflow: "RetailFlow's revenue job overwrites the day's partition so a rerun never doubles revenue.", followup: "How do you make an insert-based load idempotent?" },
      { q: "What belongs in CI vs CD for a data project?", a: "CI: lint, unit tests, dbt/data tests on a CI schema, build artifacts. CD: deploy artifacts to environments, run migrations, post-deploy checks, promotion gates.", why: "Mixing them blurs where failures should stop a change.", mistake: "Running deploys inside the 'test' stage so a test failure still deploys.", retailflow: "RetailFlow tests the revenue model in CI and only deploys the passing artifact in CD.", followup: "Where in this split does a data-quality gate sit?" },
      { q: "How do you test infrastructure code before applying it?", a: "Run <code>terraform validate</code> and <code>plan</code> in CI, use policy checks (OPA/Sentinel), and review the plan output in the PR before <code>apply</code>.", why: "An unreviewed apply can destroy or recreate live resources.", mistake: "Auto-applying on merge without reviewing the plan.", retailflow: "RetailFlow posts the Terraform plan on the PR so reviewers see the warehouse change before apply.", followup: "How do you prevent a plan from accidentally destroying stateful resources?" }
    ],
    proficient: [
      { q: "Design a CI/CD strategy for 500 Airflow DAGs across teams.", a: "Use a monorepo or per-domain repos with a shared DAG-factory library; CI runs import/lint/unit tests only on changed DAGs, packages DAGs as a versioned artifact or image, and CD promotes via git-sync/bundle per environment with team-scoped RBAC and required checks.", why: "At 500 DAGs, full re-testing and manual deploys don't scale and ownership blurs.", mistake: "One giant pipeline that re-parses everything on every change, taking hours.", retailflow: "RetailFlow's revenue DAG is one of hundreds; only its folder is tested and redeployed on change.", followup: "How do you enforce per-team ownership and blast-radius limits?" },
      { q: "How would you architect environment promotion for a data platform end to end?", a: "Immutable artifacts (images, dbt package, DAB) built once in CI; identical infra via Terraform modules per environment; the same artifact promoted dev→staging→prod with config/secrets injected per stage; gates of tests + data quality + approvals between stages.", why: "It guarantees prod runs exactly what was validated, with a clear audit trail.", mistake: "Environment-specific rebuilds and hand-tweaked infra that drift apart.", retailflow: "RetailFlow ships one revenue artifact through three identical-shaped environments.", followup: "Where do you inject environment config so the artifact stays immutable?" },
      { q: "A dbt uniqueness test fails but unit tests pass — should Terraform still deploy infra?", a: "No. The quality gate should block the whole promotion; a failed data check means the change isn't safe to ship even though code compiles.", why: "Deploying infra for a change with bad data risks corrupting prod tables.", mistake: "Treating infra and data as independent gates so infra deploys anyway.", retailflow: "RetailFlow halts the revenue release when the <code>order_id</code> uniqueness test fails.", followup: "How do you sequence infra, code, and data deploys to fail safely?" },
      { q: "How do you roll back a data pipeline that produced wrong numbers for three days?", a: "Redeploy the previous code artifact, then reprocess the affected partitions from raw/bronze data (or restore from snapshots), validate against expected metrics, and communicate the correction downstream.", why: "Code rollback alone leaves the wrong rows in place.", mistake: "Only reverting the PR and assuming historical tables self-correct.", retailflow: "RetailFlow rolls back the image and reprocesses three days of revenue partitions from raw orders.", followup: "What data architecture (medallion, partitioning, snapshots) makes this reprocessing cheap?" },
      { q: "Design a blue/green deployment for a pipeline sharing one warehouse.", a: "Deploy the new job to a green schema/dataset, run it in parallel, validate outputs against blue, then atomically swap consumers (views/synonyms) to green; keep blue for instant rollback.", why: "The shared warehouse means you isolate at the schema/view layer, not the compute layer.", mistake: "Sharing tables directly so green pollutes blue's data mid-cutover.", retailflow: "RetailFlow builds revenue into a green schema, compares to blue, then repoints the dashboard view.", followup: "How do schema-level blue/green and app-level blue/green differ?" },
      { q: "How do you implement canary for a data transformation, not a web service?", a: "Run the new logic on a sampled subset of keys/partitions or in shadow mode alongside the old, compare distributions and totals, and widen only if metrics match within tolerance.", why: "Data canaries validate correctness of outputs, not just latency.", mistake: "Canarying by traffic percentage when the risk is wrong aggregates, not load.", retailflow: "RetailFlow shadow-runs the new net-revenue logic and diffs totals against production before switching.", followup: "What tolerance and metrics decide promotion for a revenue calc?" },
      { q: "How do you manage Terraform state at scale across many teams?", a: "Remote backend with locking, state split by domain/environment (small blast radius), workspaces or separate state files, strict access controls, and no cross-state manual edits.", why: "One giant state file is slow, risky, and a contention point.", mistake: "A single monolithic state everyone applies against, causing locks and huge blast radius.", retailflow: "RetailFlow keeps warehouse, networking, and jobs in separate states per environment.", followup: "How do you share outputs between split states safely?" },
      { q: "How do you prevent secret sprawl across GitHub Actions, Terraform, Databricks, and Airflow?", a: "Centralize in one vault/managed identity, use OIDC for cloud auth, reference secrets by name at runtime, rotate automatically, and scan repos/images for leaks.", why: "Copies of secrets in each tool multiply exposure and rotation pain.", mistake: "Duplicating the same warehouse password into four systems.", retailflow: "RetailFlow's four tools all pull the warehouse credential from one vault via short-lived tokens.", followup: "How do you rotate a credential used by four systems without downtime?" },
      { q: "Design CI/CD so a schema change and its dependent dbt models deploy atomically.", a: "Gate the change behind dbt contracts, run the migration and model build in one transactional deploy where possible, use expand/contract for non-atomic stores, and block promotion if any contract or test fails.", why: "A half-applied schema change breaks downstream consumers.", mistake: "Deploying the migration and the model in separate uncoordinated pipelines.", retailflow: "RetailFlow's <code>refund_amount</code> type change and the revenue model ship together, gated by a contract.", followup: "What do you do when the store can't wrap the migration in a transaction?" },
      { q: "How do you test a whole pipeline end to end in CI without prod data?", a: "Seed synthetic or masked fixtures, run the full extract→transform→test flow against an ephemeral environment, assert on outputs and data-quality rules, then tear it down.", why: "Unit tests miss integration and orchestration bugs.", mistake: "Pointing 'integration' tests at prod, risking data and cost.", retailflow: "RetailFlow spins up an ephemeral schema, loads seeded orders, and asserts computed revenue.", followup: "How do you generate representative synthetic data for revenue tests?" },
      { q: "How do you choose between GitOps (Argo CD) and pipeline-push deploys for data infra?", a: "GitOps suits declarative Kubernetes resources needing continuous reconciliation and audit; pipeline-push suits imperative steps (dbt runs, migrations, bundle deploys). Many platforms use both — GitOps for cluster state, pipelines for data jobs.", why: "Forcing everything into one model creates friction.", mistake: "Trying to model a stateful dbt run as pure declarative GitOps.", retailflow: "RetailFlow uses Argo CD for Airflow manifests and pipeline-push for the dbt revenue build.", followup: "How do you keep the two models from fighting over the same resources?" },
      { q: "How do you design rollback for a Databricks Asset Bundle deployment?", a: "Tag each bundle deploy by version, keep prior job definitions retrievable, redeploy the previous bundle version on failure, and pair with data reprocessing for any bad output.", why: "Rolling back the job definition doesn't fix data it already wrote.", mistake: "Deleting the old bundle version so you can't cleanly revert.", retailflow: "RetailFlow redeploys the prior revenue bundle target and reprocesses the affected run.", followup: "How do you keep bundle versions and their data outputs correlated?" },
      { q: "What's your strategy for zero-downtime dbt deployments on a live warehouse?", a: "Build into a shadow schema, run tests there, then atomically swap via views/clone/table rename so consumers never see partial state.", why: "Rebuilding in place exposes consumers to half-built tables.", mistake: "Running <code>dbt run</code> directly on prod tables during business hours.", retailflow: "RetailFlow builds revenue into a staging schema and swaps the prod view once tests pass.", followup: "How does zero-copy clone help here?" },
      { q: "How do you handle a poison DAG that fails at parse time and blocks the scheduler?", a: "Validate DAG parsing in CI (a DagBag import test), deploy DAGs atomically, and use a canary scheduler or dag-processor isolation so one bad file can't halt all scheduling.", why: "A single import error can stop every DAG from being scheduled.", mistake: "Deploying DAG files straight to prod without an import test.", retailflow: "RetailFlow's CI fails the PR if the revenue DAG raises any import error.", followup: "How does the standalone DAG processor limit blast radius?" },
      { q: "Design observability for a data CI/CD platform.", a: "Track deploy frequency, lead time, change-fail rate, MTTR (DORA), plus data freshness, volume anomalies, test pass rates, and lineage; alert on both pipeline failure and silently-wrong data.", why: "Green pipelines can still ship wrong numbers.", mistake: "Monitoring only job success, not data correctness.", retailflow: "RetailFlow alerts when revenue deviates from its forecast band even if the job 'succeeded'.", followup: "Which DORA metric best reflects data-pipeline health, and why is it insufficient alone?" },
      { q: "How do you enforce that prod always matches reviewed, tested code?", a: "Protected <code>main</code> with required checks and reviews, deploy only from <code>main</code> via automation (no manual prod access), immutable artifacts, and GitOps/audit so drift is detected and reconciled.", why: "Manual prod changes are the top source of untraceable incidents.", mistake: "Allowing engineers hotfix access to prod outside the pipeline.", retailflow: "RetailFlow revokes human write access to the prod revenue job; only the pipeline deploys.", followup: "How do you allow emergency hotfixes without breaking this guarantee?" },
      { q: "How do you version and promote ML/analytics artifacts alongside code?", a: "Treat models/manifests as versioned artifacts in a registry, pin them by digest, promote the exact version through environments, and record the code+data+config lineage for each.", why: "Reproducibility requires pinning all three: code, data, and artifact.", mistake: "Retraining or recompiling per environment, so prod differs from tested.", retailflow: "RetailFlow promotes the exact compiled dbt manifest that CI validated, by digest.", followup: "What lineage do you capture to reproduce a given prod run?" },
      { q: "How do you design CI for a monorepo mixing dbt, Terraform, Airflow, and app code?", a: "Path-based triggers so only affected components run, per-component pipelines with shared caching, a dependency graph for cross-cutting changes, and independent but coordinated deploys.", why: "Running every tool on every change is slow and noisy.", mistake: "One monolithic workflow that runs Terraform on a docs typo.", retailflow: "A change under <code>transforms/</code> triggers dbt CI but not the Terraform plan.", followup: "How do you handle a change that spans dbt and Terraform together?" },
      { q: "How do you safely apply Terraform that would recreate a stateful resource?", a: "Detect the destructive plan in CI, require explicit approval, use <code>prevent_destroy</code> lifecycle, <code>moved</code> blocks or state <code>import</code> to avoid recreation, and take a backup/snapshot first.", why: "An unnoticed recreate can wipe the warehouse or its data.", mistake: "Auto-applying a plan that shows a destroy/recreate of a database.", retailflow: "A rename triggers a recreate of RetailFlow's warehouse; a <code>moved</code> block preserves it instead.", followup: "When do you use <code>moved</code> vs <code>import</code> vs <code>prevent_destroy</code>?" },
      { q: "How do you structure quality gates so infra, code, and data all must pass to promote?", a: "A single promotion gate aggregates: build+unit tests, static analysis/security, Terraform plan policy checks, and data-quality tests — all must be green, and the same artifact advances only if every check passes.", why: "Independent gates let one dimension ship while another is broken.", mistake: "Deploying infra green while data tests are red.", retailflow: "RetailFlow's revenue change advances only when code, Sonar, plan policy, and dbt tests are all green.", followup: "How do you avoid a slow serial gate becoming a bottleneck?" },
      { q: "How do you implement progressive delivery for a nightly batch pipeline?", a: "Shadow-run the new logic nightly alongside prod, diff outputs over several runs, then cut over once diffs are within tolerance; keep the old path warm for rollback.", why: "Batch pipelines can't canary by live traffic, so you validate over multiple runs.", mistake: "Cutting over after a single successful shadow run.", retailflow: "RetailFlow shadow-runs new revenue logic for a week, comparing totals before switching.", followup: "How many clean runs justify cutover, and what invalidates them?" },
      { q: "How do you contain the blast radius of a bad secret rotation across the platform?", a: "Rotate with overlapping validity (new key active before old is revoked), roll out per environment, monitor auth-failure metrics, and automate rollback of the rotation.", why: "A hard cutover breaks every consumer simultaneously.", mistake: "Revoking the old credential before all systems pick up the new one.", retailflow: "RetailFlow issues a new warehouse credential, verifies all four tools authenticate, then revokes the old.", followup: "How does dual-key overlap enable zero-downtime rotation?" },
      { q: "How do you decide Kubernetes vs managed services for running data workloads?", a: "Choose Kubernetes for multi-tenant, bursty, custom orchestration needing portability; choose managed (Databricks jobs, cloud Airflow) when ops burden outweighs control benefits. Match to team maturity and scale.", why: "Kubernetes power comes with real operational cost.", mistake: "Adopting Kubernetes for a handful of nightly jobs.", retailflow: "RetailFlow runs the revenue job on managed Databricks, reserving Kubernetes for elastic worker fleets.", followup: "What operational capabilities must a team have before self-managing Kubernetes?" },
      { q: "How do you test and gate a PySpark job's performance, not just correctness?", a: "Add regression checks on runtime, shuffle, and data volume against baselines in CI/staging, fail on significant regressions, and profile the plan for skew and wide shuffles.", why: "A correct job that got 10x slower can blow the SLA.", mistake: "Gating only on correctness, letting a skew regression reach prod.", retailflow: "RetailFlow flags the revenue job when its staging runtime regresses beyond a threshold.", followup: "How do you catch data skew before it hits the 7 AM SLA?" },
      { q: "How do you architect rollback-friendly medallion tables?", a: "Immutable partitioned bronze as source of truth, idempotent recomputable silver/gold, snapshots or time-travel on curated tables, so any layer can be rebuilt or reverted deterministically.", why: "If curated layers are recomputable from bronze, rollback is a reprocess, not a restore-from-backup scramble.", mistake: "Mutating gold in place with no way to rebuild it from raw.", retailflow: "RetailFlow rebuilds revenue in gold from immutable bronze orders for any affected day.", followup: "How does table time-travel complement recomputability?" },
      { q: "How do you coordinate a release that spans app code, dbt models, and infra?", a: "Feature-flag the change, deploy infra and backward-compatible code first, then data models, verify each stage's gate, and flip the flag last; design every step to be independently revertible.", why: "Big-bang cross-layer releases are hard to reason about and roll back.", mistake: "Deploying all layers at once so a failure is ambiguous to revert.", retailflow: "RetailFlow deploys the schema and infra, then the revenue model, then enables the new dashboard field.", followup: "Why deploy infra before the code that depends on it?" },
      { q: "How do you prevent CI/CD from becoming the biggest security hole?", a: "Least-privilege scoped identities, OIDC over static keys, pinned action/plugin versions, isolated ephemeral runners, secret scanning, and required review on pipeline definitions themselves.", why: "Pipelines hold deploy credentials to everything; a compromised workflow is catastrophic.", mistake: "Running untrusted third-party actions with full deploy permissions.", retailflow: "RetailFlow pins every Action to a SHA and scopes the deploy identity to the revenue job only.", followup: "Why pin third-party actions by commit SHA rather than tag?" },
      { q: "How do you validate a Helm/Argo CD change before it hits the cluster?", a: "Lint and template the chart, run <code>kubectl --dry-run</code>/kubeconform against the API schema, diff the rendered manifests in the PR, and let Argo CD preview the sync before auto-applying.", why: "A bad manifest can take down the orchestrator.", mistake: "Merging chart value changes without rendering and diffing them.", retailflow: "RetailFlow diffs the rendered Airflow manifests in the PR before Argo CD syncs.", followup: "How does Argo CD's diff view help catch drift and mistakes?" },
      { q: "How do you design a CI/CD process that a data team of mixed skill levels can actually follow?", a: "Golden-path templates and reusable workflows, sensible defaults, a paved-road CLI, guardrails (required checks, protected branches) rather than tribal knowledge, and clear docs plus fast feedback.", why: "A process only juniors can't use becomes a bottleneck or gets bypassed.", mistake: "Relying on senior engineers to hand-configure every pipeline.", retailflow: "RetailFlow gives each team a templated pipeline so shipping a revenue-model change is one PR.", followup: "How do guardrails differ from gatekeeping, and why does it matter?" },
      { q: "How do you keep CI fast as the repo and test suite grow?", a: "Cache dependencies and build layers, run only tests affected by the change (dbt <code>state:modified+</code>, pytest selection), parallelize with a matrix, split slow integration/E2E into a separate stage or nightly run, and fail fast on the cheapest checks first.", why: "Slow CI kills the feedback loop — engineers batch changes or bypass checks, which is exactly what CI exists to prevent.", mistake: "Rebuilding everything and running the full suite on every tiny PR until CI takes 40 minutes.", retailflow: "RetailFlow's PR CI builds only the changed dbt models and their downstream, keeping revenue-change feedback under a few minutes; the full-refresh suite runs nightly.", followup: "What's the risk of only testing 'changed' models, and how do you mitigate it?" }
    ]
  };

  var LEVELS = [
    { key: "beginner", label: "Beginner" },
    { key: "intermediate", label: "Intermediate" },
    { key: "proficient", label: "Proficient" }
  ];

  NS.registerModule({
    id: "interview",
    title: "Interview Questions",

    render: function (container) {
      var self = this;
      self._active = "beginner";
      self._search = "";

      container.innerHTML =
        '<div class="module-header animate-fade-in-up">' +
          '<div class="module-eyebrow">Learning · Interview Prep</div>' +
          '<h1 class="module-title gradient-text">Interview Questions</h1>' +
          '<p class="module-subtitle">Expandable question bank across the whole RetailFlow CI/CD stack — ' +
          'answer, why it matters, the common mistake, a RetailFlow scenario, and a harder follow-up.</p>' +
        '</div>' +
        '<div class="gloss-toolbar">' +
          '<input type="text" class="iv-search gloss-search" placeholder="Search questions…" aria-label="Search interview questions" />' +
          '<span class="gloss-count iv-count"></span>' +
        '</div>' +
        '<div class="cm-level-tabs iv-tabs">' +
          LEVELS.map(function (l, i) {
            return '<button class="cm-level-tab' + (i === 0 ? ' active' : '') +
              '" data-level="' + l.key + '">' + l.label + '</button>';
          }).join("") +
        '</div>' +
        '<div class="iv-list" style="margin-top:var(--space-5);display:flex;flex-direction:column;gap:12px;"></div>';

      var list = container.querySelector(".iv-list");
      var input = container.querySelector(".iv-search");
      var count = container.querySelector(".iv-count");
      var tabs = container.querySelectorAll(".iv-level, .cm-level-tab");

      function row(label, value) {
        return '<div class="iv-a-row" style="margin-bottom:8px;font-size:var(--text-sm);line-height:1.55;">' +
          '<span style="display:inline-block;min-width:130px;font-weight:700;color:var(--text-primary);vertical-align:top;">' +
          label + '</span>' +
          '<span style="color:var(--text-secondary);">' + value + '</span>' +
        '</div>';
      }

      function draw() {
        var items = DATA[self._active] || [];
        var q = self._search.trim().toLowerCase();
        var shown = items.filter(function (it) {
          return !q || it.q.toLowerCase().indexOf(q) !== -1;
        });

        if (shown.length === 0) {
          list.innerHTML = '<div class="gloss-empty">No questions match your search.</div>';
        } else {
          list.innerHTML = shown.map(function (it, idx) {
            return '<div class="iv-item" style="border:1px solid var(--border-default);border-radius:var(--radius-md);overflow:hidden;background:var(--bg-1);">' +
              '<button class="iv-q" data-idx="' + idx + '" aria-expanded="false" ' +
                'style="width:100%;text-align:left;padding:14px 16px;background:transparent;border:none;color:var(--text-primary);font-weight:600;font-size:0.98rem;cursor:pointer;line-height:1.45;">' +
                '<span style="color:var(--airflow);margin-right:8px;">▸</span>' + it.q +
              '</button>' +
              '<div class="iv-a" style="display:none;padding:4px 16px 16px 16px;border-top:1px solid var(--border-default);">' +
                row('Answer', it.a) +
                row('Why it matters', it.why) +
                row('Common mistake', it.mistake) +
                row('RetailFlow', it.retailflow) +
                row('Follow-up', it.followup) +
              '</div>' +
            '</div>';
          }).join("");

          var qbtns = list.querySelectorAll(".iv-q");
          qbtns.forEach(function (btn) {
            btn.addEventListener("click", function () {
              var panel = btn.nextElementSibling;
              var open = panel.style.display !== "none";
              panel.style.display = open ? "none" : "block";
              btn.setAttribute("aria-expanded", open ? "false" : "true");
              var arrow = btn.querySelector("span");
              if (arrow) arrow.textContent = open ? "▸" : "▾";
            });
          });
        }
        count.textContent = shown.length + " of " + items.length + " questions";
      }

      function onInput() { self._search = input.value; draw(); }
      input.addEventListener("input", onInput);

      function onTab(e) {
        var btn = e.target.closest(".cm-level-tab");
        if (!btn) return;
        self._active = btn.getAttribute("data-level");
        var all = container.querySelectorAll(".cm-level-tab");
        all.forEach(function (b) { b.classList.remove("active"); });
        btn.classList.add("active");
        draw();
      }
      var tabBar = container.querySelector(".iv-tabs");
      tabBar.addEventListener("click", onTab);

      self._input = input;
      self._onInput = onInput;
      self._tabBar = tabBar;
      self._onTab = onTab;

      draw();
    },

    destroy: function () {
      if (this._input && this._onInput) this._input.removeEventListener("input", this._onInput);
      if (this._tabBar && this._onTab) this._tabBar.removeEventListener("click", this._onTab);
      this._input = null; this._tabBar = null; this._onInput = null; this._onTab = null;
    }
  });
})();
